CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	username VARCHAR(20) NOT NULL UNIQUE,
	password TEXT NOT NULL,
	email VARCHAR(80) UNIQUE,
	picture TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT NOW()
);