CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS buy_list(
	id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid() ,
	product_id UUID NOT NULL,
	amount INTEGER NOT NULL DEFAULT 0,
	weight DECIMAL,
	unity_price NUMERIC NOT NULL DEFAULT 0,
	is_bought BOOLEAN NOT NULL DEFAULT FALSE,
	date_add TIMESTAMP NOT NULL DEFAULT NOW(),
	user_id UUID NOT NULL,
	
	FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)
